### ISSUE TITLE
This is something wrong with action client on ros2 of humble version

### ISSUE THREAD

**Issue by lioSgr** [JaehyunShim/ros2_tutorial_cpp#10]
Hello, i have builled this code, and find something.
The way of writing the action client may have changed in the humble version, i can not build successfull.
I change something like this, it builded pass.

```
// void goal_response_callback(std::shared_future<ClientGoalHandleFibonacci::SharedPtr> future)
  void goal_response_callback(const ClientGoalHandleFibonacci::SharedPtr & future)
  {
    auto goal_handle = future.get();
    if (!goal_handle) {
      RCLCPP_ERROR(this->get_logger(), "Goal was rejected by server");
    } else {
      RCLCPP_INFO(this->get_logger(), "Goal accepted by server, waiting for result");

      goal_sent_ = true;
    }
  }
```
I am looking for the truth reason.

By the way, are u the anuthor of "vscode-ros2"? I like this extension so much! But it is not update long time, and the code is not exist. And the extension use the same way writing.I want to fix it.

**Comment by JaehyunShim** [comment]
Hi

Thank you so much for your interest in my code and the extension. I am still using Foxy for my codebase and haven't updated things to Humble yet. I will do my best to make time for it. Thank you. 

Best regards,
Jaehyun

**Comment by lioSgr** [comment]
I am very happy for receiving your reply.
I was not thinking carefully,my apologies.
Thank u for opening your extension.

Best wishes for u.
This is lio, the new robot developer
